kind = "mobile"
previewPath = "/mobile/"
title = "Przepiśnik LowStyleLife"
version = "1.0.0"
id = "artifacts/przepisnik-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 22680

[services.development]
run = "pnpm --filter @workspace/przepisnik-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/przepisnik-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/przepisnik-mobile", "run", "serve" ]

[services.env]
PORT = "22680"
BASE_PATH = "/mobile/"
